spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  profiles:
    active: dev