spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  profiles:
    active: dev
  kafka:
    bootstrapServers: kafka:9092
#    bootstrapServers: localhost:9092
#    bootstrap-servers: host.docker.internal:9093
    producer:
      topic: REST-api